### PR TITLE
Added Cloudmersive Deep Learning APIs

### PR DESCRIPTION
**Pull request by Cloudmersive**
Added the Cloudmersive Deep Learning APIs

### CODE REVIEW

**Comment by denispeplin** [comment]
@Cloudmersive , this file is supposed to be autogenerated.

**Comment by Cloudmersive** [comment]
@denispeplin Where is it autogenerated from?  Is there another file to edit instead?

**Comment by denispeplin** [comment]
@Cloudmersive , I have a builder for this repository: https://github.com/awesomerank/rank
But it's not being supported for a long time and I haven't run it for a while.
So there is no point changing anything there too unless you want to take over and start building these pages again.

**Comment by Cloudmersive** [comment]
Roger.  So if that pipeline isn't live, what do you think then about merging this PR?

**Comment by denispeplin** [comment]
@Cloudmersive , merged.

**Pull request merged**
